name: gpp
channels:
  - conda-forge
dependencies:
  - python=3.8
  - typer==0.7.0
  - ray
  - ray-tune
  - optuna
  - pydantic<2.0.0
  - scikit-learn==1.1.3
  - seaborn==0.11.0
  - multipledispatch==0.6.0
  - statsmodels==0.13.2
  - scipy
  - openpyxl==3.0.10
  - pandas==1.5.2
  - joblib==1.2.0
  - flaml==1.0.14
  - numpy==1.23.5
  - xgboost==1.6.2
  - threadpoolctl==3.1.0
  - matplotlib==3.5.2
  - pre-commit
  - fastapi
  - uvicorn
  - python-multipart
  - dash
  - sqlalchemy
  - passlib
  - python-jose[cryptography]
  - bcrypt
  - python-dotenv
  - rich
  - mlflow
  - imbalanced-learn
  - sphinx
  - furo
  - m2r2
  - sphinx-autobuild
  - sphinx-basic-ng
  - sphinx-rtd-theme
  - sphinxcontrib-apidoc
  - sphinxcontrib-napoleon
